DROP TABLE IF EXISTS DATA_RECORDS CASCADE;
DROP SEQUENCE IF EXISTS DATA_RECORDS_DATARECORDS_ID_SEQ;

CREATE TABLE DATA_RECORDS
(
  DATARECORDS_ID NUMBER PRIMARY KEY,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  ALIAS VARCHAR(20),
  EMPLOYEE_NUMBER VARCHAR(40),
  CREDIT_CARD_NUMBER NUMBER NOT NULL
);

CREATE SEQUENCE DATA_RECORDS_DATARECORDS_ID_SEQ START WITH 1 INCREMENT BY 1;